Practice_List/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls'))
]

bookmark/urls.py
from django.urls import path

from bookmark.views import BookmarkList, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkList.as_view(), name='list'),  # {% url 'bookmark:list' %}
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

bookmark/models.py
from django.db import models
from django.urls import reverse


class Bookmark(models.Model):
    site_name = models.CharField(max_length=20)
    url = models.URLField('Site URL')

    def __str__(self):
        return "제목: " + self.site_name + ", URL: " + self.url

    def get_absolute_url(self):
        return reverse('bookmark:detail', kwargs={'pk': self.id})   # {% url 'bookmark:detail' pk=bookmark.id %}

bookmark/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from bookmark.models import Bookmark


class BookmarkList(ListView):  # bookmark_list.html
    model = Bookmark
    paginate_by = 3


class BookmarkCreateView(CreateView):  # bookmark_form.html
    model = Bookmark
    fields = ['site_name', 'url']  # <form>
    template_name_suffix = '_create'  # bookmark_create.html
    success_url = reverse_lazy('bookmark:list')


class BookmarkDetailView(DetailView):
    model = Bookmark


class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']       #<form>
    template_name_suffix = '_update'    # bookmark_update.html
    success_url = reverse_lazy('bookmark:list')


class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div>진짜 지울래? {{ bookmark }}</div>
    <button type="submit" class="btn btn-danger btn-sm">sure</button>
</form>
    <button onclick="history.back()" class="btn btn-info btn-sm">Cancel</button>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}Add{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add bookmark" class="btn btn-primary btn-sm">
</form>
    <button onclick="history.back()" class="btn btn-info btn-sm">Cancel</button>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}detail{% endblock %}

{% block content %}
{{ bookmark.site_name }} <p></p>
{{ bookmark.url }}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}List{% endblock %}

{% block content %}
    <a href="{% url 'bookmark:add' %}" class="btn btn-primary btn-sm">Add Bookmark</a>
    <p></p>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Site</th>
            <th>URL</th>
            <th>Modify</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
            {% for bookmark in bookmark_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.site_name }}</a></td>
                    <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a></td>
                    <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                    <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block pagination %}
    {% if is_paginated %}
    <ul class="pagination pagination-sm justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
        {% else %}
            <li class="page-item disabled"><a href="" class="page-link">Previous</a></li>
        {% endif %}
        <!-- 127.0.0.1/bookmark/?page=숫자 -->
        {% for page in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == forloop.counter %} active{% endif %}">
            <a href="{{ request.path }}?page={{ forloop.counter }}" class="page-link">{{ forloop.counter }}</a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a href="" class="page-link">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}Update{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-success btn-sm">Modify</button>
</form>
    <button onclick="history.back()" class="btn btn-info btn-sm">Cancel</button>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark {% block title %}{% endblock %}</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'mystyle.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
    {% block pagination %}
    {% endblock %}
</body>
</html>